import React from 'react'
import Card from './Card'

const Main = () => {

    let items = [
        { name: "Bukhara", src: "/Allitems/item1.jpeg", alt: "item", address: "Chanakyapuri", rating: 5 },
        { name: "Indian Accent", src: "/Allitems/item2.jpeg", alt: "item", address: "Lodhi Road", rating: 4 },
        { name: "Karim's", src: "/Allitems/item3.jpeg", alt: "item", address: "Jama Masjid", rating: 3 },
        { name: "Saravana Bhavan", src: "/Allitems/item4.jpg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Moti Mahal", src: "/Allitems/item5.jpeg", alt: "item", address: "Daryaganj", rating: 5 },
        { name: "Dum Pukht", src: "/Allitems/item6.jpg", alt: "item", address: "Chanakyapuri", rating: 4 },
        { name: "Big Chill", src: "/Allitems/item7.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Parikrama", src: "/Allitems/item8.jpeg", alt: "item", address: "Connaught Place", rating: 3 },
        { name: "Rajinder Da Dhaba", src: "/Allitems/item9.jpeg", alt: "item", address: "Safdarjung Enclave", rating: 4 },
        { name: "SodaBottleOpenerWala", src: "/Allitems/item10.jpeg", alt: "item", address: "Khan Market", rating: 3 },
        { name: "Pind Balluchi", src: "/Allitems/item11.jpg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Punjab Grill", src: "/Allitems/item12.jpeg", alt: "item", address: "Saket", rating: 5 },
        { name: "The Spice Route", src: "/Allitems/item13.jpeg", alt: "item", address: "Janpath", rating: 5 },
        { name: "United Coffee House", src: "/Allitems/item14.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Biryani Blues", src: "/Allitems/item15.jpeg", alt: "item", address: "Lajpat Nagar", rating: 3 },
        { name: "Minar", src: "/Allitems/item16.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Haldiram's", src: "/Allitems/item17.jpeg", alt: "item", address: "Karol Bagh", rating: 3 },
        { name: "Lazeez Affaire", src: "/Allitems/item18.jpg", alt: "item", address: "Chanakyapuri", rating: 4 },
        { name: "Ricos", src: "/Allitems/item19.jpg", alt: "item", address: "Kamla Nagar", rating: 5 },
        { name: "Masala Library", src: "/Allitems/item20.jpg", alt: "item", address: "Janpath", rating: 4 },
        { name: "AnnaMaya", src: "/Allitems/item21.jpeg", alt: "item", address: "Aerocity", rating: 3 },
        { name: "Tamra", src: "/Allitems/item22.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Sevilla", src: "/Allitems/item23.jpeg", alt: "item", address: "Aurangzeb Road", rating: 5 },
        { name: "Oh! Calcutta", src: "/Allitems/item24.jpeg", alt: "item", address: "Nehru Place", rating: 3 },
        { name: "Fio Cookhouse", src: "/Allitems/item25.jpeg", alt: "item", address: "Nehru Place", rating: 4 },
        { name: "Sagar Ratna", src: "/Allitems/item26.jpeg", alt: "item", address: "Defence Colony", rating: 3 },
        { name: "Yeti", src: "/Allitems/item27.jpeg", alt: "item", address: "Hauz Khas Village", rating: 5 },
        { name: "Diggin", src: "/Allitems/item28.jpeg", alt: "item", address: "Anand Lok", rating: 4 },
        { name: "Mamagoto", src: "/Allitems/item29.jpeg", alt: "item", address: "Khan Market", rating: 3 },
        { name: "Cafe Lota", src: "/Allitems/item30.jpeg", alt: "item", address: "Pragati Maidan", rating: 5 },
        { name: "Nando's", src: "/Allitems/item31.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Olive Bar & Kitchen", src: "/Allitems/item32.jpeg", alt: "item", address: "Mehrauli", rating: 5 },
        { name: "Bercos", src: "/Allitems/item33.jpeg", alt: "item", address: "Connaught Place", rating: 3 },
        { name: "Gulati", src: "/Allitems/item34.jpeg", alt: "item", address: "Pandara Road", rating: 4 },
        { name: "Lodi - The Garden Restaurant", src: "/Allitems/item35.jpeg", alt: "item", address: "Lodhi Road", rating: 5 },
        { name: "Wenger's", src: "/Allitems/item36.jpeg", alt: "item", address: "Connaught Place", rating: 3 },
        { name: "Monkey Bar", src: "/Allitems/item37.jpeg", alt: "item", address: "Vasant Kunj", rating: 4 },
        { name: "Farzi Cafe", src: "/Allitems/item38.jpeg", alt: "item", address: "Connaught Place", rating: 5 },
        { name: "The Beer Cafe", src: "/Allitems/item39.jpeg", alt: "item", address: "Saket", rating: 3 },
        { name: "Barbeque Nation", src: "/Allitems/item40.jpeg", alt: "item", address: "Janakpuri", rating: 4 },
        { name: "Pa Pa Ya", src: "/Allitems/item41.jpeg", alt: "item", address: "Select Citywalk", rating: 5 },
        { name: "The Project", src: "/Allitems/item42.jpg", alt: "item", address: "Lodhi Garden", rating: 3 },
        { name: "Town Hall", src: "/Allitems/item43.jpeg", alt: "item", address: "Khan Market", rating: 4 },
        { name: "Warehouse Cafe", src: "/Allitems/item44.jpeg", alt: "item", address: "Connaught Place", rating: 5 },
        { name: "Sattvik", src: "/Allitems/item45.jpeg", alt: "item", address: "Saket", rating: 3 },
        { name: "Elma's Bakery", src: "/Allitems/item46.jpeg", alt: "item", address: "Hauz Khas Village", rating: 4 },
        { name: "Rose Cafe", src: "/Allitems/item47.jpeg", alt: "item", address: "Saket", rating: 5 },
        { name: "Lord of the Drinks", src: "/Allitems/item48.jpeg", alt: "item", address: "Connaught Place", rating: 3 },
        { name: "Kake Da Hotel", src: "/Allitems/item49.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Paatra", src: "/Allitems/item50.jpeg", alt: "item", address: "New Friends Colony", rating: 5 },
        { name: "Andrea's Eatery", src: "/Allitems/item51.jpeg", alt: "item", address: "Saket", rating: 3 },
        { name: "The Big Yellow Door", src: "/Allitems/item52.jpeg", alt: "item", address: "Satya Niketan", rating: 4 },
        { name: "Smoke House Deli", src: "/Allitems/item53.jpeg", alt: "item", address: "Vasant Kunj", rating: 5 },
        { name: "Le Cirque", src: "/Allitems/item54.jpeg", alt: "item", address: "Chanakyapuri", rating: 4 },
        { name: "Guppy", src: "/Allitems/item55.jpeg", alt: "item", address: "Lodhi Colony", rating: 3 },
        { name: "Social", src: "/Allitems/item56.jpeg", alt: "item", address: "Hauz Khas Village", rating: 5 },
        { name: "Cafe Delhi Heights", src: "/Allitems/item57.jpeg", alt: "item", address: "DLF Promenade", rating: 4 },
        { name: "Wok in the Clouds", src: "/Allitems/item58.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Varq", src: "/Allitems/item59.jpeg", alt: "item", address: "Taj Mahal Hotel", rating: 3 },
        { name: "Ambrosia Bliss", src: "/Allitems/item60.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Pasta Bowl Company", src: "/Allitems/item61.jpeg", alt: "item", address: "Gurgaon", rating: 5 },
        { name: "Thai High", src: "/Allitems/item62.jpeg", alt: "item", address: "Mehrauli", rating: 3 },
        { name: "The Artful Baker", src: "/Allitems/item63.jpeg", alt: "item", address: "Khan Market", rating: 4 },
        { name: "The Artful Baker", src: "/Allitems/item64.jpeg", alt: "item", address: "Khan Market", rating: 3 },
        { name: "Dilli Haat", src: "/Allitems/item65.jpeg", alt: "item", address: "INA", rating: 4 },
        { name: "Dilli Haat", src: "/Allitems/item66.jpeg", alt: "item", address: "INA", rating: 3 },
        { name: "Wok in the Clouds", src: "/Allitems/item67.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Manhattan", src: "/Allitems/item68.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Savage", src: "/Allitems/item69.jpeg", alt: "item", address: "Saket", rating: 5 },
        { name: "The Hull", src: "/Allitems/item70.jpg", alt: "item", address: "Hauz Khas", rating: 3 },
        { name: "Rico's", src: "/Allitems/item71.jpeg", alt: "item", address: "Kamla Nagar", rating: 4 },
        { name: "The 3rd Space", src: "/Allitems/item72.jpeg", alt: "item", address: "Lajpat Nagar", rating: 5 },
        { name: "Sahara", src: "/Allitems/item73.jpeg", alt: "item", address: "Connaught Place", rating: 3 },
        { name: "Moti Mahal", src: "/Allitems/item74.jpg", alt: "item", address: "Daryaganj", rating: 4 },
        { name: "Rajma Chawal", src: "/Allitems/item75.jpeg", alt: "item", address: "Janakpuri", rating: 5 },
        { name: "Barista", src: "/Allitems/item76.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "The Barbecue Company", src: "/Allitems/item77.jpg", alt: "item", address: "Nehru Place", rating: 3 },
        { name: "Swagath", src: "/Allitems/item78.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Roti Roti", src: "/Allitems/item79.jpeg", alt: "item", address: "Saket", rating: 4 },
        { name: "Cafe Coffee Day", src: "/Allitems/item80.jpeg", alt: "item", address: "DLF Mall", rating: 3 },
        { name: "Pind Balluchi", src: "/Allitems/item81.jpeg", alt: "item", address: "Connaught Place", rating: 5 },
        { name: "Qutub", src: "/Allitems/item82.jpeg", alt: "item", address: "Mehrauli", rating: 4 },
        { name: "Desi Vibes", src: "/Allitems/item83.jpg", alt: "item", address: "Hauz Khas", rating: 3 },
        { name: "Zaffran", src: "/Allitems/item84.jpeg", alt: "item", address: "Saket", rating: 4 },
        { name: "New Town Cafe", src: "/Allitems/item85.jpeg", alt: "item", address: "Aerocity", rating: 5 },
        { name: "Dum Pukht", src: "/Allitems/item86.jpeg", alt: "item", address: "Chanakyapuri", rating: 3 },
        { name: "Dum Pukht", src: "/Allitems/item87.jpeg", alt: "item", address: "Chanakyapuri", rating: 4 },
        { name: "Farzi Cafe", src: "/Allitems/item88.jpeg", alt: "item", address: "Connaught Place", rating: 5 },
        { name: "Yummy Tummy", src: "/Allitems/item89.jpeg", alt: "item", address: "Khan Market", rating: 3 },
        { name: "Chutney Mary", src: "/Allitems/item90.jpg", alt: "item", address: "Janpath", rating: 4 },
        { name: "Café Rouge", src: "/Allitems/item91.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "The Colony Bistro", src: "/Allitems/item92.jpeg", alt: "item", address: "Lajpat Nagar", rating: 4 },
        { name: "The Curry House", src: "/Allitems/item93.jpeg", alt: "item", address: "DLF Mall", rating: 3 },
        { name: "Famous Indian Restaurant", src: "/Allitems/item94.jpeg", alt: "item", address: "Safdarjung Enclave", rating: 5 },
        { name: "New York Slice", src: "/Allitems/item95.jpeg", alt: "item", address: "Saket", rating: 4 },
        { name: "Santoshi", src: "/Allitems/item96.jpeg", alt: "item", address: "Hauz Khas", rating: 3 },
        { name: "Bangalore Express", src: "/Allitems/item97.jpeg", alt: "item", address: "Connaught Place", rating: 5 },
        { name: "The Great Kabab Factory", src: "/Allitems/item98.jpg", alt: "item", address: "Saket", rating: 4 },
        { name: "The Big Chill Cafe", src: "/Allitems/item99.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Punjabi Grill", src: "/Allitems/item100.jpeg", alt: "item", address: "Lajpat Nagar", rating: 3 },
        { name: "Odeon Social", src: "/Allitems/item101.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Haldiram's", src: "/Allitems/item102.jpeg", alt: "item", address: "Karol Bagh", rating: 5 },
        { name: "Café Turtle", src: "/Allitems/item103.jpeg", alt: "item", address: "Khan Market", rating: 4 },
        { name: "Lajpat Nagar", src: "/Allitems/item104.jpeg", alt: "item", address: "Lajpat Nagar", rating: 3 },
        { name: "Haldiram's", src: "/Allitems/item105.jpeg", alt: "item", address: "Karol Bagh", rating: 5 },
        { name: "Haldiram's", src: "/Allitems/item106.jpg", alt: "item", address: "Karol Bagh", rating: 4 },
        { name: "The English Cafe", src: "/Allitems/item107.jpg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Cafe Monkey Bar", src: "/Allitems/item108.jpg", alt: "item", address: "Hauz Khas Village", rating: 4 },
        { name: "Olive Bar & Kitchen", src: "/Allitems/item109.jpg", alt: "item", address: "Mehrauli", rating: 5 },
        { name: "Delhi Haat", src: "/Allitems/item110.jpeg", alt: "item", address: "INA", rating: 3 },
        { name: "Café Coffee Day", src: "/Allitems/item111.jpeg", alt: "item", address: "DLF Mall", rating: 4 },
        { name: "Chutney Mary", src: "/Allitems/item112.jpeg", alt: "item", address: "Janpath", rating: 3 },
        { name: "Cafe Coffee Day", src: "/Allitems/item113.jpeg", alt: "item", address: "DLF Mall", rating: 5 },
        { name: "Punjabi Tadka", src: "/Allitems/item114.jpeg", alt: "item", address: "Saket", rating: 4 },
        { name: "Café Imperial", src: "/Allitems/item115.jpeg", alt: "item", address: "Connaught Place", rating: 5 },
        { name: "The Grill Room", src: "/Allitems/item116.jpeg", alt: "item", address: "Chanakyapuri", rating: 3 },
        { name: "Golden Dragon", src: "/Allitems/item117.jpeg", alt: "item", address: "Saket", rating: 4 },
        { name: "Tandoor", src: "/Allitems/item118.jpeg", alt: "item", address: "Saket", rating: 5 },
        { name: "Urban Desi", src: "/Allitems/item119.jpeg", alt: "item", address: "Hauz Khas", rating: 4 },
        { name: "The Great Kabab Factory", src: "/Allitems/item120.jpeg", alt: "item", address: "Saket", rating: 5 },
        { name: "Punjabi Zaika", src: "/Allitems/item121.jpeg", alt: "item", address: "Nehru Place", rating: 3 },
        { name: "Fusion", src: "/Allitems/item122.jpg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Chaayos", src: "/Allitems/item123.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Amour Bistro", src: "/Allitems/item124.jpeg", alt: "item", address: "Hauz Khas Village", rating: 3 },
        { name: "Bangalore Express", src: "/Allitems/item125.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "The Big Chill Cafe", src: "/Allitems/item126.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Kebabs & Curries", src: "/Allitems/item127.jpeg", alt: "item", address: "Saket", rating: 3 },
        { name: "Café MRP", src: "/Allitems/item128.jpg", alt: "item", address: "DLF Mall", rating: 4 },
        { name: "Pizza Hut", src: "/Allitems/item129.jpeg", alt: "item", address: "Janakpuri", rating: 5 },
        { name: "Ritz", src: "/Allitems/item130.jpeg", alt: "item", address: "Mehrauli", rating: 4 },
        { name: "Saffron", src: "/Allitems/item131.jpeg", alt: "item", address: "Chanakyapuri", rating: 3 },
        { name: "The Royal China", src: "/Allitems/item132.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Cafe Fresco", src: "/Allitems/item133.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Zaiqa", src: "/Allitems/item134.jpeg", alt: "item", address: "Saket", rating: 3 },
        { name: "Wok on Fire", src: "/Allitems/item135.jpeg", alt: "item", address: "Vasant Kunj", rating: 4 },
        { name: "Chowk", src: "/Allitems/item136.jpeg", alt: "item", address: "Hauz Khas", rating: 5 },
        { name: "Cafe Dori", src: "/Allitems/item137.jpeg", alt: "item", address: "Saket", rating: 3 },
        { name: "The Yellow Chilli", src: "/Allitems/item138.jpeg", alt: "item", address: "Nehru Place", rating: 4 },
        { name: "Al Bake", src: "/Allitems/item139.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Café Coffee Day", src: "/Allitems/item140.jpeg", alt: "item", address: "DLF Mall", rating: 3 },
        { name: "Moet's", src: "/Allitems/item141.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Grandma's Kitchen", src: "/Allitems/item142.jpeg", alt: "item", address: "Hauz Khas Village", rating: 5 },
        { name: "Hawkers", src: "/Allitems/item143.jpeg", alt: "item", address: "Janpath", rating: 3 },
        { name: "Gourmet Delight", src: "/Allitems/item144.jpeg", alt: "item", address: "Saket", rating: 4 },
        { name: "The Crave", src: "/Allitems/item145.jpeg", alt: "item", address: "Nehru Place", rating: 5 },
        { name: "Goodies", src: "/Allitems/item146.jpeg", alt: "item", address: "Khan Market", rating: 3 },
        { name: "Garam Dharam", src: "/Allitems/item147.jpeg", alt: "item", address: "Janakpuri", rating: 4 },
        { name: "Rolls King", src: "/Allitems/item148.jpeg", alt: "item", address: "DLF Mall", rating: 5 },
        { name: "Uncle's Kitchen", src: "/Allitems/item149.jpeg", alt: "item", address: "Saket", rating: 3 },
        { name: "Indian Kitchen", src: "/Allitems/item150.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Cafe Mystique", src: "/Allitems/item151.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Madhulika", src: "/Allitems/item152.jpeg", alt: "item", address: "Safdarjung Enclave", rating: 3 },
        { name: "Madhulika", src: "/Allitems/item153.jpeg", alt: "item", address: "Safdarjung Enclave", rating: 4 },
        { name: "The Tandoori Kitchen", src: "/Allitems/item154.jpeg", alt: "item", address: "Hauz Khas Village", rating: 5 },
        { name: "The Burger House", src: "/Allitems/item155.jpeg", alt: "item", address: "Connaught Place", rating: 4 },
        { name: "Cafe Delight", src: "/Allitems/item156.jpeg", alt: "item", address: "Khan Market", rating: 5 },
        { name: "Bento", src: "/Allitems/item157.jpeg", alt: "item", address: "Saket", rating: 3 },
        { name: "Sushi Point", src: "/Allitems/item158.jpeg", alt: "item", address: "Nehru Place", rating: 4 },
        { name: "Quick Bites", src: "/Allitems/item159.jpeg", alt: "item", address: "Janakpuri", rating: 5 },
        { name: "Dilli 6", src: "/Allitems/item160.jpeg", alt: "item", address: "Karol Bagh", rating: 3 },
        { name: "Sweet Treats", src: "/Allitems/item161.jpeg", alt: "item", address: "Saket", rating: 4 },
        { name: "Fusion Kitchen", src: "/Allitems/item162.jpeg", alt: "item", address: "Connaught Place", rating: 5 },
        { name: "Punjabi Khaana", src: "/Allitems/item163.jpeg", alt: "item", address: "Hauz Khas", rating: 3 },
        { name: "Café Scrumptious", src: "/Allitems/item164.jpeg", alt: "item", address: "Janpath", rating: 4 },
       
 ]

  return (
    <div className="min-w-full">
    <div className="w-[1100px]  mx-auto p-6 ">
      <div className=" flex">
        <div className="text-2xl font-bold">Restaurants with online food delivery in Delhi</div>

        
      </div>

      <div className="flex flex-wrap gap-8 mt-4">
             {items.map(((el, index) =>{
                return (
                    <div key={index}>
                         <Card  {...el}/>
                    </div>
                )
             }))}
       
      </div>
      <hr className="mt-10" />
    </div>
   
  </div>
  )
}

export default Main